<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Api.Domain\Api.Domain.csproj" />
    <ProjectReference Include="..\Api.Data\Api.Data.csproj" />
    <ProjectReference Include="..\Api.Infrastructure\Api.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
  </ItemGroup>
</Project>
