<Project Sdk="Microsoft.NET.Sdk.Web">


  <ItemGroup>
    <Content Include="frontend/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>



  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

    <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.18" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="7.0.12" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Api.Domain\Api.Domain.csproj" />
    <ProjectReference Include="..\Api.Service\Api.Service.csproj" />
    <ProjectReference Include="..\Api.CrossCutting\Api.CrossCutting.csproj" />
    <ProjectReference Include="..\Api.Infrastructure\Api.Infrastructure.csproj" />
  </ItemGroup>

</Project>
